name = "email-moderation-production"
main = "src/index.ts"
compatibility_date = "2024-11-21"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "development"
DEBUG_MODE = "false"
DISCORD_APPROVAL_CHANNEL_ID = "1458372243905187840"
DISCORD_ROUTE_APPROVAL_CHANNEL_ID = "1458920160424628305"
DISCORD_FEEDBACK_CHANNEL_ID = "1459470631379796113"

[[kv_namespaces]]
binding = "EMAIL_APPROVAL_KV"
id = "ab785c626c3847fca5118ab58ff211e1"

[[kv_namespaces]]
binding = "ROUTE_APPROVAL_KV"
id = "592b2fafe2a94a1ebdf08b12a3b3caa7"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true
